<?php
// Obtener la fecha y hora actual
$fecha_hora_actual = date("Y-m-d H:i:s");
?>

<!DOCTYPE html>
<html lang="es">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Fecha y Hora Actual</title>
</head>
<body>
    <h1>Fecha y Hora Actual</h1>
    <p>Fecha y hora actual: <?php echo $fecha_hora_actual; ?></p>
</body>
</html>
